---
- hosts:  all
  become:  true
  tasks:
  -
   blockinfile:
       path: /etc/security/pwquality.conf
       block: |
         minlen = 8
         difok = 1
         dcredit = -1
         lcredit = 1
         ocredit = 1
       backup: yes

